set(_SKLIB_INCLDIR
    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    set(_SK_PLATFORM_WIN ON)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    set(_SK_PLATFORM_DARWIN ON)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    set(_SK_PLATFORM_LINUX ON)
endif()

set(_SK_MODULE_NAME ${PROJECT_NAME})
